#!/bin/bash
#
# Dart Version Manager
# author: Chris Bracken <chris@bracken.jp>

DVM_ROOT="$HOME/.dvm"

_dvm_usage() {
  echo "usage: dvm <command> [<args>]"
  echo ""
  echo "Commands:"
  echo "   install    Install a Dart version"
  echo "   list       List installed Dart versions"
  echo "   listall    List all available Dart versions"
  echo "   use        Select a Dart version to use"
  return 1
}

_dvm_create_dirs() {
  mkdir -p "$DVM_ROOT/darts" > /dev/null 2>&1
  mkdir -p "$DVM_ROOT/environments" > /dev/null 2>&1
}

dvm_use() {
  if [[ $# < 1 ]]; then
    echo "usage: dvm use <version> [--default]"
    return 1
  fi

  local version=$1
  local default=$2
  shift

  if [[ "$default" == "--default" ]]; then
    local defaults="$DVM_ROOT/environments/default"
    echo 'export DVM_ROOT; DVM_ROOT="$DVM_ROOT"' > "$defaults"
    echo "PATH=\"\$DVM_ROOT/darts/$version/bin:\$PATH\"" >> "$defaults"
  fi

  if [[ ! -d "$DVM_ROOT/darts/$version" ]]; then
    echo "ERROR: version not found. Try 'dvm install $version'"
    return 1
  fi
  PATH="$DVM_ROOT/darts/$version/bin:$PATH"
}

dvm_list() {
  for v in $(find "$DVM_ROOT/darts" -maxdepth 1 ! -path "$DVM_ROOT/darts" -type d); do
    echo $(basename $v)
  done
}

dvm_listall() {
  local api_uri="https://www.googleapis.com/storage/v1/b/dart-archive/o"
  local query="prefix=channels/stable/release/&delimiter=/"
  curl -s "$api_uri?$query" | \
      grep "channels/stable/release/" | \
      sed -e "s@.*/stable/release/@@;s@/.*@@"
}

dvm_install() {
  if [[ $# < 1 ]]; then
    echo "usage: dvm install <version>"
    return 1
  fi

  curl=$(which curl)
  if [[ ! -x "$curl" ]]; then
    echo "ERROR: curl is required but was not found on PATH."
    return 1
  fi

  local version=$1
  shift 

  if [[ -d "$DVM_ROOT/darts/$version" ]]; then
    echo "ERROR: version $version is already installed"
    return 1
  fi

  case $(uname) in
    Darwin)
      local sdk_archive=dartsdk-macos-x64-release.zip
      local dartium_archive=dartium-macos-ia32-release.zip
      ;;
    Linux)
      local sdk_archive=dartsdk-linux-x64-release.zip
      local dartium_archive=dartium-linux-x64-release.zip
      ;;
    *)
      echo "ERROR: unable to determine OS."
      return 1
      ;;
  esac
  
  # Create tmp workspace.
  tmpdir=$(mktemp -d)
  pushd $tmpdir > /dev/null

  # Download SDK.
  local dl_uri="https://storage.googleapis.com/dart-archive/channels/stable/release"
  local base_uri="$dl_uri/$version"
  curl -f -O "$base_uri/sdk/$sdk_archive"
  if [[ $? -ne 0 ]]; then
    echo "ERROR: unable to download Dart SDK. Are you sure that version exists?"
    popd > /dev/null
    rm -rf $tmpdir
    return 1
  fi
  unzip $sdk_archive
  version=$(<dart-sdk/version)

  # Move SDK under $DVM_ROOT/darts.
  if [[ ! -d "$DVM_ROOT/darts/$version" ]]; then
    mv dart-sdk "$DVM_ROOT/darts/$version"
  fi

  # Download Dartium.
  curl -f -O "$base_uri/dartium/$dartium_archive"
  if [[ $? -ne 0 ]]; then
    echo "ERROR: unable to download Dartium. But hey, at least you got the SDK."
  else
    unzip $dartium_archive
    if [[ ! -d "$DVM_ROOT/darts/$version/dartium" ]]; then
      local dartium_dir="$(find . -maxdepth 1 ! -path . -type d)"
      mv "$dartium_dir" "$DVM_ROOT/darts/$version/dartium"
    fi

    # Create Dartium symlink.
    pushd "$DVM_ROOT/darts/$version/bin" > /dev/null
    case $(uname) in
      Darwin)
        echo "#!/bin/bash" > dartium
        echo "open $DVM_ROOT/darts/$version/dartium/Chromium.app" >> dartium
        chmod ugo+x dartium
        ;;
      Linux)
        ln -s ../dartium/chrome dartium
        ;;
    esac
    popd > /dev/null
  fi

  # Clean up.
  popd > /dev/null
  rm -rf $tmpdir
}

dvm() {
  if [[ -z "$DVM_ROOT" ]]; then
    echo "ERROR: DVM_ROOT not set. Please source \$DVM_ROOT/scripts/dvm."
    return 1
  fi
  if [[ ! -d "$DVM_ROOT" ]]; then
    echo "ERROR: DVM_ROOT does not exist. Please reinstall DVM."
    return 1
  fi
  _dvm_create_dirs

  if [[ $# < 1 ]]; then
    _dvm_usage
    return 1
  fi
  cmd=$1
  shift
  if [[ "$cmd" == "use" ]]; then
    dvm_use "$@"
  elif [[ "$cmd" == "list" ]]; then
    dvm_list "$@"
  elif [[ "$cmd" == "listall" ]]; then
    dvm_listall "$@"
  elif [[ "$cmd" == "install" ]]; then
    dvm_install "$@"
  else
    _dvm_usage
  fi
}

if [[ -e "$DVM_ROOT/environments/default" ]]; then
  . "$DVM_ROOT/environments/default"
fi
